var CouncilMembers = [
{
	name: "Raghav Agarwal",
	email: "@nsit.net.in",
	title: "Executive",
	position: "General Secretary",
	department: "SAC",
	branch: "COE",
	year: 2016,
	image: "images/small/2016/raghav",
	description: "Founding Batch",
	active: 0
},
{
	name: "Shashwat Deepali Nagar",
	email: "@nsit.net.in",
	title: "Executive",
	position: "Vice President",
	department: "Academic Affairs",
	branch: "BT",
	year: 2016,
	image: "images/small/2016/shashwat",
	description: "Founding Batch",
	active: 0
},
{
	name: "Prateek Jain",
	email: "@nsit.net.in",
	title: "Executive",
	position: "Vice President",
	department: "External Affairs",
	branch: "ECE",
	year: 2016,
	image: "images/small/2016/prateek",
	description: "Founding Batch",
	active: 0
},
{
	name: "Ashish Kothari",
	email: "@nsit.net.in",
	title: "Executive",
	position: "Vice President",
	department: "Student Affairs",
	branch: "??",
	year: 2016,
	image: "images/small/2016/ashish",
	description: "Founding Batch",
	active: 0
},
{
	name: "Mamik Sharma",
	email: "@nsit.net.in",
	title: "Executive",
	position: "Vice President",
	department: "Student Activities",
	branch: "ICE",
	year: 2016,
	image: "images/small/2016/mamik",
	description: "Founding Batch",
	active: 0
},
{
	name: "Shubham Midha",
	email: "shubhamm.ec@nsit.net.in",
	title: "Executive",
	position: "General Secretary",
	department: "SAC",
	branch: "ECE",
	year: 2017,
	image: "images/small/2017/shubham",
	description: "",
	active: 0
},
{
	name: "Ishaan Dube",
	email: "ishaand.mp@nsit.net.in",
	title: "Executive",
	position: "General Secretary",
	department: "SAC",
	branch: "MPAE",
	year: 2018,
	image: "images/small/ishaan",
	description: "",
	active: 1
},
{
	name: "Jayati Nandan",
	email: "jayatin.ec@nsit.net.in",
	title: "Executive",
	position: "Vice President",
	department: "Student Affairs",
	branch: "ECE",
	year: 2018,
	image: "images/small/jayati",
	description: "",
	active: 1
},
{
	name: "Mohit Munjal",
	email: "mohitm.co@nsit.net.in",
	title: "Executive",
	position: "Vice President",
	department: "External Affairs",
	branch: "COE",
	year: 2018,
	image: "images/small/mohit",
	description: "",
	active: 1
},
{
	name: "Priyam Sarpal",
	email: "priyams.ic@nsit.net.in",
	title: "Executive",
	position: "Vice President",
	department: "Student Activities",
	branch: "ICE",
	year: 2018,
	image: "images/small/priyam",
	description: "",
	active: 1
},
{
	name: "Ankush Babbar",
	email: "ankushb.co@nsit.net.in",
	title: "Executive",
	position: "Vice President",
	department: "Academic Affairs",
	branch: "COE",
	year: 2018,
	image: "images/small/ankush",
	description: "",
	active: 1
},
{
	name: "Nikita Chawla",
	email: "nikitac.it@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Affairs",
	branch: "IT",
	year: 2019,
	image: "images/small/nikita",
	description: "",
	active: 1
},
{
	name: "Varshika Gambhir",
	email: "varshikag.co@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Affairs",
	branch: "COE",
	year: 2019,
	image: "images/small/varshika",
	description: "",
	active: 1
},
{
	name: "Anuj Juneja",
	email: "anujj.ic@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Affairs",
	branch: "ICE",
	year: 2019,
	image: "images/small/anuj",
	description: "",
	active: 1
},
{
	name: "Harshit Luthra",
	email: "harshitl.ec@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Affairs",
	branch: "ECE",
	year: 2019,
	image: "images/small/harshit",
	description: "",
	active: 1
},
{
	name: "Tanvi Sharma",
	email: "tanvis.co@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Affairs",
	branch: "COE",
	year: 2019,
	image: "images/small/tanvi",
	description: "",
	active: 1
},
{
	name: "Shantanu Agrawal",
	email: "shantanua.co@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "External Affairs",
	branch: "COE",
	year: 2019,
	image: "images/small/shantanu",
	description: "",
	active: 1
},
{
	name: "Vishesh Balani",
	email: "visheshb.ic@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "External Affairs",
	branch: "ICE",
	year: 2019,
	image: "images/small/vishesh",
	description: "",
	active: 1
},
{
	name: "Rashmi Gehi",
	email: "rashmig.ec@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "External Affairs",
	branch: "ECE",
	year: 2019,
	image: "images/small/rashmi",
	description: "",
	active: 1
},
{
	name: "Manik Kapoor",
	email: "manikk.mp@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "External Affairs",
	branch: "MPAE",
	year: 2019,
	image: "images/small/manik",
	description: "",
	active: 1
},
{
	name: "Ishan Ambardar",
	email: "ishana.co@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Activities",
	branch: "COE",
	year: 2019,
	image: "images/small/ishan",
	description: "",
	active: 1
},
{
	name: "Aditya Barthwal",
	email: "adityab.ec@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Activities",
	branch: "ECE",
	year: 2019,
	image: "images/small/aditya",
	description: "",
	active: 1
},
{
	name: "Amogh Hassija",
	email: "amoghh.it@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Activities",
	branch: "IT",
	year: 2019,
	image: "images/small/amogh",
	description: "",
	active: 1
},
{
	name: "Shivin Saluja",
	email: "shivins.co@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Activities",
	branch: "COE",
	year: 2019,
	image: "images/small/shivin",
	description: "",
	active: 1
},
{
	name: "Anurag B. Singh",
	email: "anuragb.mp@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Student Activities",
	branch: "MPAE",
	year: 2019,
	image: "images/small/anurag",
	description: "",
	active: 1
},
{
	name: "Udit K. Agarwal",
	email: "uditk.ec@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Academic Affairs",
	branch: "ECE",
	year: 2019,
	image: "images/small/udit",
	description: "",
	active: 1
},
{
	name: "Abhishek Arora",
	email: "abhisheka.ic@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Academic Affairs",
	branch: "ICE",
	year: 2019,
	image: "images/small/abhishek",
	description: "",
	active: 1
},
{
	name: "Raina Banerjee",
	email: "rainab.ec@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Academic Affairs",
	branch: "ECE",
	year: 2019,
	image: "images/small/raina",
	description: "",
	active: 1
},
{
	//g or g1 email
	name: "Akshita Gupta",
	email: "akshitag.bt@nsit.net.in",
	title: "Secretaries",
	position: "Member",
	department: "Academic Affairs",
	branch: "BT",
	year: 2019,
	image: "images/small/akshita",
	description: "",
	active: 1
}
];

Template.membersList.helpers({
	/*member: function() {
		return councilMembers.find();
	}*/
	members: CouncilMembers,
	//members: () => CouncilMembers.find(),
});

